  title: "John F. Bartlett - AI Strategy & Implementation Consultant"
description: "Strategic AI Implementation That Delivers Real Results"
baseurl: ""
url: "https://johnbartlett.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Navigation
navigation:
  - title: "Services"
    url: "#services"
  - title: "Results"
    url: "#results"
  - title: "Industries"
    url: "#industries"
  - title: "Development Expertise"
    url: "/development-expertise/"
  - title: "About"
    url: "#about"
  - title: "Contact"
    url: "#contact"

# Site version
version: 3.2.49

