# _config.yml

title: "John Bartlett's Blog"
description: "A professional blog using the Minimal Mistakes Jekyll theme."
theme: minimal-mistakes-jekyll
lang: en-US

plugins:
  - jekyll-feed
  - jekyll-include-cache

# Site settings
remote_theme: "mmistakes/minimal-mistakes"
header_pages:
  - title: "About"
    url: "/about/"
  - title: "Contact"
    url: "/contact/"
